### ISSUE TITLE
DVHA v1.0

### ISSUE THREAD

**Issue by cutright** [cutright/DVH-Analytics#108]
I'd like to release a `v1.0` by the end of the year.  I won't be working on any new feature requests until then (feel free to post anyway though), will focus only on stability and wrapping up the currently posted feature requests:
 - [x] [Import DICOM files associated by directory](https://github.com/cutright/DVH-Analytics/issues/106)
 - [x] [Machine Learning without going through Regression module](https://github.com/cutright/DVH-Analytics/issues/107)
 - [x] [Edge backend for MSW](https://github.com/cutright/DVH-Analytics/issues/90)  
 - [x] [DVHA backend documentation](https://github.com/cutright/DVH-Analytics/issues/126)

However, please continue to report any bugs or TPS support issues.

Getting non-HFS was a big feature I wanted for `1.0`, the other one was getting away from Internet Explorer emulation on Windows.  If I can get the `wx.html2` to work with the latest `wxpython`, I may add that too if it's stable.  If anyone has had any luck with [this](https://discuss.wxpython.org/t/ms-edge-backend-for-webview/34953), please let me know! I was able to see the Edge backend option, but none of my webviews show for me as of `wxPython-4.1.1a1.dev5026`.  I may ping Robin if I can't get the latest build to work either.  I couldn't even run his demo code... so something might awry.

**Comment by cutright** [comment]
Everything on the above wishlist is available as `v0.9.3`.  The following release will be `v1.0.rc1`!
