### ISSUE TITLE
MemoryError during DICOM Import on MS Windows and Linux

### ISSUE THREAD

**Issue by cutright** [cutright/DVH-Analytics#26]
**Bug**: Importing too many plans at once on MS Windows may result in memory errors, sometimes preventing subsequent queries within the same DVHA session.

**Current work-around**: Import fewer plans at a time (typically <= 10) and restart DVHA afterwards if needed.

I've not noticed memory errors when no plans have been imported in a session (unless your query includes nearly every DVH in the database).  I have a database of 80 patients in SQLite3 (DVHA v0.6.7dev only at the moment) and the same 80 in a PostgreSQL database with no plotting issues.

I've been able to import all 80 at once on macOS.  Not sure if Linux has this issue or not.

**Comment by cutright** [comment]
With 0253e04, `dvha.db.DICOM_Parser` objects now have a `clear_loaded_data` function that sets all parsed DICOM data to `None` and stores the few properties that are needed before reloading DICOM data from file.

Reading and parsing is now significantly faster (at least on MSW). I was able to import 30 plans in one shot.

Still getting memory issues, but this is good progress.

**Comment by cutright** [comment]
`dicompylercore.dicomparser.DicomParser().GetStructureCoordinates()` can throw `MemoryError` on MSW for large structures (e.g., External, Skin).
https://github.com/cutright/DVH-Analytics/blob/21eb925eba3850905fbbc0a806b15f9ff42d0f7c/dvha/db/dicom_parser.py#L889-L898

I took External and Skin out of the ROI_Map so that they aren't imported, but now I eventually run into memory errors when reloading from DICOM files with `dvha.db.DICOM_Parser.load_from_file()`.

https://github.com/cutright/DVH-Analytics/blob/21eb925eba3850905fbbc0a806b15f9ff42d0f7c/dvha/models/import_dicom.py#L1190-L1198

Issue may be related to OS settings?  Monitoring with Windows Task Manager Performance shows slight memory leak over time, but always has more memory available than is used by DVHA.

**Comment by cutright** [comment]
There is definitely a memory leak, at least on MSW, and I'm not sure where yet.  Doesn't appear to exist on macOS.

**PC used for testing in prior posts**:
Windows 7 Enterprise SP1
Intel i5 3.2GHz
8GB RAM
64-bit OS

**PC used for testing in this post**:
Windows 7 Ultimate SP1
Intel Xeon E5 2.4GHz
32GB RAM
64-bit OS

RAM usage for the import thread tripled (to ~3.5GB) before crashing on the Xeon PC, made it through 20 plans. I'm making it though 4 plans on the i5 PC. I believe the 30 plans quoted before was when I still had some try/except catches for MemoryError that I've turned off since trying to track down the leak.

**Comment by bastula** [comment]
Try upgrading to pydicom 1.4.0 or 1.4.1. There was an issue resolved here: https://github.com/pydicom/pydicom/issues/994 that may be relevant.

FWIW I was running into the same issue on linux, but the RAM on my box was only 2 or 4 GB.

**Comment by cutright** [comment]
Thanks Adit, I was just about to post a diagnosis pointing to pydicom. The output below is based on the example at python.org for tracemallac. I’m currently on pydicom 1.4.0 on MSW and apparently 1.4.1 on Mac, so I’ll give 1.4.1 on MSW a shot this afternoon.

pydicom.filereader.py appears to be biggest the culprit, but pydicom in general too.

```
(venv) C:\Users\dcutright\PycharmProjects\DVH-Analytics>python dvha_app.py
-----------------------------------------------------------------
Top 10 lines
#1: models\import_dicom.py:1138: 0.9 KiB
    if study_uid not in list(study_uids):
#2: models\import_dicom.py:1139: 0.6 KiB
    study_uids[study_uid] = []
#3: models\import_dicom.py:735: 0.6 KiB
    del self.parsed_dicom_data
#4: models\import_dicom.py:1183: 0.5 KiB
    self.import_study(plan_uid, final_plan_in_study=plan_uid == plan_uid_set[-1])
#5: models\import_dicom.py:736: 0.4 KiB
    dlg = ImportStatusDialog(self.terminate)
#6: models\import_dicom.py:1140: 0.4 KiB
    study_uids[study_uid].append(plan_uid)
#7: models\import_dicom.py:1111: 0.4 KiB
    self.import_studies()
#8: models\import_dicom.py:1151: 0.4 KiB
    study_uids = self.get_study_uids()
#9: models\import_dicom.py:1209: 0.3 KiB
    snapshot = tracemalloc.take_snapshot()
#10: wx\core.py:1772: 0.2 KiB
    wx.PyEvent.__init__(clone, self)
5 other: 0.3 KiB
Total allocated size: 4.9 KiB
-----------------------------------------------------------------
Top 10 lines
#1: pydicom\filereader.py:196: 62542.2 KiB
    value = (fp_read(length) if length > 0
#2: pydicom\multival.py:43: 12207.9 KiB
    return self.type_constructor(x) if x != '' else x
#3: pydicom\valuerep.py:550: 10746.2 KiB
    splitup = val.split("\\")
#4: pixel_data_handlers\numpy_handler.py:351: 1949.5 KiB
    return arr.copy()
#5: pydicom\multival.py:50: 1466.5 KiB
    self._list.append(type_constructor(x))
#6: pydicom\dataset.py:1896: 784.0 KiB
    object.__setattr__(self, name, value)
#7: pydicom\dataelem.py:241: 478.1 KiB
    self.tag = tag
#8: pydicom\dataelem.py:782: 413.6 KiB
    raw.length == 0xFFFFFFFF, already_converted=True)
#9: pydicom\filereader.py:395: 343.1 KiB
    ds = Dataset(raw_data_elements)
#10: lib\linecache.py:137: 323.7 KiB
    lines = fp.readlines()
667 other: 2332.5 KiB
Total allocated size: 93587.5 KiB
-----------------------------------------------------------------
Top 10 lines
#1: pydicom\filereader.py:196: 153711.0 KiB
    value = (fp_read(length) if length > 0
#2: pydicom\multival.py:43: 29202.6 KiB
    return self.type_constructor(x) if x != '' else x
#3: pydicom\valuerep.py:550: 25788.0 KiB
    splitup = val.split("\\")
#4: pixel_data_handlers\numpy_handler.py:351: 7429.5 KiB
    return arr.copy()
#5: pydicom\multival.py:50: 3511.8 KiB
    self._list.append(type_constructor(x))
#6: pydicom\dataset.py:1896: 2381.1 KiB
    object.__setattr__(self, name, value)
#7: pydicom\dataelem.py:241: 1306.7 KiB
    self.tag = tag
#8: pydicom\filereader.py:395: 1089.2 KiB
    ds = Dataset(raw_data_elements)
#9: pydicom\dataelem.py:782: 1076.3 KiB
    raw.length == 0xFFFFFFFF, already_converted=True)
#10: lib\linecache.py:137: 676.2 KiB
    lines = fp.readlines()
683 other: 4886.0 KiB
Total allocated size: 231058.4 KiB
-----------------------------------------------------------------
Top 10 lines
#1: pydicom\filereader.py:196: 186642.1 KiB
    value = (fp_read(length) if length > 0
#2: pydicom\multival.py:43: 36928.2 KiB
    return self.type_constructor(x) if x != '' else x
#3: pydicom\valuerep.py:550: 32603.8 KiB
    splitup = val.split("\\")
#4: pixel_data_handlers\numpy_handler.py:351: 10655.9 KiB
    return arr.copy()
#5: pydicom\multival.py:50: 4442.8 KiB
    self._list.append(type_constructor(x))
#6: pydicom\dataset.py:1896: 3106.5 KiB
    object.__setattr__(self, name, value)
#7: pydicom\dataelem.py:241: 1684.5 KiB
    self.tag = tag
#8: pydicom\filereader.py:395: 1415.8 KiB
    ds = Dataset(raw_data_elements)
#9: pydicom\dataelem.py:782: 1407.1 KiB
    raw.length == 0xFFFFFFFF, already_converted=True)
#10: pydicom\tag.py:238: 874.5 KiB
    return BaseTag(long_value)
681 other: 5892.4 KiB
Total allocated size: 285653.6 KiB
-----------------------------------------------------------------
Top 10 lines
#1: pydicom\filereader.py:196: 246766.9 KiB
    value = (fp_read(length) if length > 0
#2: pydicom\multival.py:43: 52744.5 KiB
    return self.type_constructor(x) if x != '' else x
#3: pydicom\valuerep.py:550: 46639.7 KiB
    splitup = val.split("\\")
#4: pixel_data_handlers\numpy_handler.py:351: 13633.5 KiB
    return arr.copy()
#5: pydicom\multival.py:50: 6333.1 KiB
    self._list.append(type_constructor(x))
#6: pydicom\dataset.py:1896: 4463.2 KiB
    object.__setattr__(self, name, value)
#7: pydicom\dataelem.py:241: 2389.2 KiB
    self.tag = tag
#8: pydicom\filereader.py:395: 2046.4 KiB
    ds = Dataset(raw_data_elements)
#9: pydicom\dataelem.py:782: 1995.3 KiB
    raw.length == 0xFFFFFFFF, already_converted=True)
#10: pydicom\tag.py:238: 1230.5 KiB
    return BaseTag(long_value)
694 other: 7632.5 KiB
Total allocated size: 385874.9 KiB
 ```

**Comment by cutright** [comment]
Still exists in pydicom 1.4.1.  :(

**Comment by bastula** [comment]
That's a bummer. I was hoping it would resolve those issues. In my instance my hack is to just spin up a new subprocess to do the parsing to avoid the memory error, so at least the memory is released. Does change the way you have to architect your code.

**Comment by cutright** [comment]
Yeah, I think a new subprocess is the way to go... luckily shouldn’t be too difficult with the current structure.

**Comment by cutright** [comment]
I was able to get around the `pydicom.read_file` bug using `multiprocessing.Pool` and completely recreating the `dvha.db.Dicom_Parser` object inside the new thread (can't pickle pydicom datasets), however I need to figure out how to send messages back to the progress dialog... I can't use `wx.CallAfter` from the thread and the `pub.sendMessage` by itself doesn't appear to be getting back to the GUI thread.

In my first test I successfully imported 40 plans at once, and I can see the memory allocation dropping after each patient dataset completes.  It seems like even the PTV distance calculation and DTH histograms are calculating without crashing too.

I could not parse more than 50 at once in the import module, prior to actual importing.  So I might have to rework the import module with pooling as well.

**Comment by cutright** [comment]
As of a798098, I was successfully able to use `pub.sendMessage` after moving to a `Queue` and `Thread` implementation instead of `multiprocessing.Pool`.  I'm able to import at least 40 plans at once now including all of the PTV Distance and DTH calculations, and including External and Skin DVH calculations again too.

To be clear, this test was on the i5 PC previously mentioned, with 8GB of RAM.

**TODO before release ready**
 - [X] Correctly update warning messages on Import DICOM module
 - [X] Address memory allocation issues during initial parsing in Import DICOM module (i.e., prior to the actual import process
 - [X] reimplement the cancel button functionality
 - [X] reimplement the file moving/copying functionality

https://github.com/cutright/DVH-Analytics/blob/a798098d05c9f89e764038aa15852c2be5564edc/dvha/models/import_dicom.py#L1286-L1325

**Comment by cutright** [comment]
I believe this issue is finally resolved. All uses of `pydicom` are now implemented in a separate thread. The downside is that every file set ends up being read-in by pydicom twice.  Will test on MSW on Monday.

I've pushed a release candidate to PyPI: [0.7.1rc1](https://pypi.org/project/dvha/0.7.1rc1/)

**Comment by cutright** [comment]
I have successfully imported 80 plans in one shot with MSW7 on an Intel i5 3.2GHz with
8GB RAM.  Will push 0.7.1 to master today.

**Comment by cutright** [comment]
Set a record today.  371 plans in one import session. Same computer mentioned in the last comment.  Pretty sure any substantial memory leaks have been squashed.  This even includes reading in DICOM headers from CTs for each patient.

RAM usage generally hovers around ~400MB.  But I'm only importing ~10 DVHs per patient.
